name: Cypress

on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        working-directory: ./step-03
      - name: Cypress run
        uses: cypress-io/github-action@v4
        working-directory: ./step-03
